### ISSUE TITLE
ESP32 and others

### ISSUE THREAD

**Issue by analogic** [Seeed-Studio/Seeed_Arduino_KCT202#4]
Hello I am trying to port lib to ESP32 Arduino branch. I've simply add ARDUINO_ARCH_ESP32 and <HardwareSerial, HardwareSerial>, and raise size of com buffers at kct202.cpp (32bit thing?) and now I am communicating with module but with issues.

It seems that original arduino SoftwareSerial is blocked at getRegisterResponAndparse until it get result (at least I expect that from examples). If I do that on esp32 it will just result instantly, proceed to next code and register empty sensor as fingerprint. So I am missing something. 

Is there any proper protocol documentation for module? 
I've also got some "Please check the error code through datasheet!", so is there any datasheet? Google is not helping me

**Comment by analogic** [comment]
Do you have datasheet of KCT203 or firmware to understand how this thing work? @Hansen0314 @Pillar1989 @IsQianGe?

**Comment by Cincinnatu** [comment]
Could you provide more information so that I can try to reproduce your issue?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
